### ISSUE TITLE
Unable to allocate large array causing OOM exception

### ISSUE THREAD

**Issue by justin-arvay** [mitchhentges/json-compose#3]
Seems to happen when reading a very large string. Looks like internally the string is limited to the max size of an Int. 

Relavent stacktrace:
```
 java.lang.OutOfMemoryError: Java heap space at java.base/java.util.Arrays.copyOf(Arrays.java:3744) at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:146) at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:722) at java.base/java.lang.StringBuilder.append(StringBuilder.java:208)

        at ca.fuzzlesoft.JsonCompose.internalStringCompose (JsonCompose.java:184)
        at ca.fuzzlesoft.JsonCompose.internalMapCompose (JsonCompose.java:107)
        at ca.fuzzlesoft.JsonCompose.internalMapCompose (JsonCompose.java:109)
        at ca.fuzzlesoft.JsonCompose.internalCollectionCompose (JsonCompose.java:144)
        at ca.fuzzlesoft.JsonCompose.internalMapCompose (JsonCompose.java:111)
        at ca.fuzzlesoft.JsonCompose.compose (JsonCompose.java:72) 
```
Also see: https://stackoverflow.com/a/13772839

**Comment by justin-arvay** [comment]
Looks to be specifically a limitation of StringBuilder.
